import type { Metadata } from "next";
import Navbar from "@/components/navbar";

import { Inter, Poppins } from "next/font/google";
import { Montserrat } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";

// const primaryFont = DM_Sans({ subsets: ["latin" ]})
// const primaryFont = Montserrat({ subsets: ["latin" ]})
const primaryFont = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={primaryFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
